# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
extends: dcc://kotlin
devcontainer:
  publish:
    image: ghcr.io/dhhyi/recipe-db-devcontainer-recipes-edit
    labels:
      org.opencontainers.image.source: https://github.com/dhhyi/recipe-db
  build:
    user:
      - RUN echo "alias gradle='./gradlew --no-daemon'" | tee -a /home/vscode/.bashrc /home/vscode/.zshrc
  ports:
    - 4000
  environment:
    TESTING: "true"
    GRAPHQL_ENDPOINT: http://traefik/graphql
    CONTEXT_PATH: /edit
  initialize: ./gradlew --no-daemon tasks
vscode:
  settings:
    # gradle.autoDetect: "off"
    peacock.remoteColor: "#ea0ff2"
  extensions:
    - johnpapa.vscode-peacock
    - GraphQL.vscode-graphql
    # - vscjava.vscode-gradle
extras:
  - traefik
  - named-volumes
namedVolumes:
  $HOME/.gradle: recipe-db-recipes-edit-gradle-user-home
  $HOME/.vaadin: recipe-db-recipes-edit-vaadin-user-home
  .gradle: recipe-db-recipes-edit-gradle
traefik:
  network: intranet
  labels:
    http:
      routers:
        recipes-edit:
          rule: PathPrefix(`/edit`)
          entrypoints: web
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: frontend
precommit: |
  ktfmt src build.gradle.kts
  ./gradlew --no-daemon compileKotlin detekt
prettier:
  ignore:
    - ROOT
    - "*.kt"
    - "*.kts"
    - "*.jar"
    - "*.png"
