# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
extends: dcc://javascript-pnpm
devcontainer:
  initialize: |
    pnpm install
    npm run codegen
  ports:
    - 4000
  environment:
    TESTING: "true"
    REST_ENDPOINT: http://traefik:3000
vscode:
  settings:
    editor.defaultFormatter: esbenp.prettier-vscode
    peacock.remoteColor: "#3d2160"
    filewatcher.commands:
      - match: "\\.gql"
        cmd: cd ${workspaceRoot} && npm run codegen
        event: onFileChange
  extensions:
    - johnpapa.vscode-peacock
    - GraphQL.vscode-graphql
    - esbenp.prettier-vscode
    - appulate.filewatcher
extras:
  - named-volumes
  - traefik
namedVolumes:
  node_modules: recipe-db-apollo-node-modules
  /home/pnpm: recipe-db-pnpm-store
traefik:
  network: intranet
  labels:
    http:
      routers:
        apollo:
          rule: PathPrefix(`/graphql`)
          entrypoints: web
      #     middlewares: apollo-stripprefix
      # middlewares:
      #   apollo-stripprefix:
      #     stripprefix:
      #       prefixes: /graphql
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: api
precommit: |
  npm run lint-schema
  npm run codegen
  npm run lint-code -- --fix
  npm run build
