#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")
#@ load("service-template.lib.yml", "service")
#@ load("traefik-service-template.lib.yml", "traefik_service")
#@ load("@ytt:struct", "struct")
#@
#@ def filter_projects(category):
#@   return [project for project in data.values.projects if project.category == category]
#@ end
#@
#@ projects = struct.make(
#@   backend=filter_projects("backend"),
#@   api=filter_projects("api"),
#@   frontend=filter_projects("frontend"),
#@   job=filter_projects("job")
#@ )
#@ options = struct.make(
#@   production=data.values.production,
#@   ci=data.values.ci
#@ )
#@
#@ deploy_projects = projects.backend + projects.api
#@ if not data.values.backendOnly:
#@   deploy_projects += projects.frontend
#@ end
#@ if not options.production:
#@   deploy_projects += projects.job
#@ end
#@
#@ def service_map():
#@   services = {"traefik": traefik_service(options.production)}
#@   for project in deploy_projects:
#@     services.update(service(project, options, projects))
#@   end
#@   return services
#@ end
#@
services:
  _: #@ template.replace(service_map())
networks:
  intranet:
    name: intranet
    external: true
#@ if options.production:
volumes:
  data:
    name: recipe-db-data
#@ end
