#!/usr/bin/env bats

load test_helper

setup() {
  setup_fixture sync-tailwind.sh
  use_mise_tools
  mkdir -p design/src example/templates
  touch design/src/component.html design/outside.html
  cat > design/.project.yaml << 'EOF'
name: design
---
tailwindSources:
  - src/component.html
  - outside.html
EOF
  cat > example/.project.yaml << 'EOF'
name: example
---
tailwindSources:
  - templates
EOF
  cat > design/Dockerfile << 'EOF'
FROM scratch
# BEGIN generated Tailwind Docker inputs
COPY obsolete /obsolete
# END generated Tailwind Docker inputs
RUN echo preserved
EOF
}

@test "resolves stylesheet-relative paths and copies only other projects into Docker" {
  run sh .scripts/sync-tailwind.sh

  [ "$status" -eq 0 ]
  cat > expected.css << 'EOF'
/* This file is generated by sync-tailwind.sh. Do not edit it manually. */

@source "../../example/templates";
@source "../outside.html";
@source "component.html";
EOF
  cmp expected.css design/src/tailwind-sources.css
  grep -Fx 'COPY ["example/templates","/example/templates"]' design/Dockerfile
  run -1 grep -F obsolete design/Dockerfile
  run -1 grep -F 'COPY ["design/' design/Dockerfile
  grep -Fx 'FROM scratch' design/Dockerfile
  grep -Fx 'RUN echo preserved' design/Dockerfile
}

@test "rejects source paths escaping the project without changing outputs" {
  cp design/Dockerfile expected.Dockerfile
  printf '%s\n' sentinel > design/src/tailwind-sources.css
  for source in /tmp ../outside templates/../outside templates/.. ..; do
    printf 'name: example\n---\ntailwindSources:\n  - %s\n' "$source" > example/.project.yaml

    run --separate-stderr sh .scripts/sync-tailwind.sh

    [ "$status" -eq 1 ]
    [ "$stderr" = "Tailwind source $source must be inside project example" ]
    cmp expected.Dockerfile design/Dockerfile
    [ "$(cat design/src/tailwind-sources.css)" = sentinel ]
  done
}

@test "rejects missing sources" {
  printf '%s\n' 'name: example' '---' 'tailwindSources: [missing]' > example/.project.yaml

  run --separate-stderr sh .scripts/sync-tailwind.sh

  [ "$status" -eq 1 ]
  [ "$stderr" = "Tailwind source example/missing must be an existing file or directory" ]
  [ ! -e design/src/tailwind-sources.css ]
}

@test "fails on missing or duplicate Docker markers without replacing the Dockerfile" {
  for markers in missing duplicate; do
    if [ "$markers" = missing ]; then
      printf '%s\n' 'FROM scratch' > design/Dockerfile
    else
      cat > design/Dockerfile << 'EOF'
FROM scratch
# BEGIN generated Tailwind Docker inputs
# END generated Tailwind Docker inputs
# BEGIN generated Tailwind Docker inputs
# END generated Tailwind Docker inputs
EOF
    fi
    cp design/Dockerfile expected.Dockerfile

    run --separate-stderr sh .scripts/sync-tailwind.sh

    [ "$status" -eq 1 ]
    [ "$stderr" = "expected exactly one marker pair in design/Dockerfile" ]
    cmp expected.Dockerfile design/Dockerfile
  done
}
