# lint-disable-line relay-page-info-spec
# lint-disable types-have-descriptions, fields-have-descriptions, arguments-have-descriptions

type Recipe {
  id: ID!
  name: String!
}

extend type Query {
  recipe(id: ID!): Recipe
  recipes: [Recipe]
}
