type Recipe {
  id: ID!
  name: String!
}

extend type Query {
  recipe(id: ID!): Recipe
  recipes: [Recipe]
}

extend type Mutation {
  deleteRecipesForTesting: Boolean

  createRecipe(value: JSON!): Recipe
  updateRecipe(id: ID!, value: JSON): Recipe
  deleteRecipe(id: ID!): Boolean
}
