input RecipeInput {
  ingredients: [IngredientInput!]
  method: String
  name: String
}

input IngredientInput {
  amount: StringOrInt
  name: String!
  optional: Boolean
  unit: String
}

type Recipe {
  id: ID!
  ingredients: [Ingredient!]
  method: String
  name: String!
}

type Ingredient {
  amount: String
  name: String!
  optional: Boolean
  unit: String
}

extend type Query {
  recipe(id: ID!): Recipe
  recipes: [Recipe]
}

extend type Mutation {
  deleteRecipesForTesting: Boolean

  createRecipe(value: RecipeInput): Recipe
  updateRecipe(id: ID!, value: RecipeInput): Recipe
  deleteRecipe(id: ID!): Boolean
}
