# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
extends: dcc://debian
devcontainer:
  name: recipe-db-recipes
  publish:
    image: ghcr.io/dhhyi/recipe-db-devcontainer-recipes
    labels:
      org.opencontainers.image.source: https://github.com/dhhyi/recipe-db
  build:
    packages:
      - autoconf
      - build-essential
      - libncurses-dev
      - libssl-dev
      - libssh-dev
      - m4
    user:
      - RUN KERL_CONFIGURE_OPTIONS="--without-javac --without-odbc --without-wx" mise use -g erlang@27.3.4.17 elixir@1.18.5-otp-27
      - RUN mkdir -p $HOME/.hex $HOME/.cache/rebar3
  initialize: |
    mix local.hex --force
    mix local.rebar --force
    mix deps.get
  ports:
    - 5000
  environment:
    LANG: C.UTF-8
    LC_ALL: C.UTF-8
    TESTING: "true"
vscode:
  settings:
    window.title: "${dirty}${rootName}${separator}${profileName}${separator}"
    peacock.remoteColor: "#db94b8"
  extensions:
    - johnpapa.vscode-peacock
    - elixir-lsp.elixir-ls
extras:
  - traefik
  - named-volumes
namedVolumes:
  $HOME/.hex: recipe-db-recipes-hex-cache
  $HOME/.cache/rebar3: recipe-db-recipes-rebar-cache
traefik:
  network: intranet
  labels:
    http:
      services:
        recipe-db-recipes:
          loadBalancer:
            healthCheck:
              interval: 10s
              timeout: 1s
              path: /health
      routers:
        recipes:
          rule: PathPrefix(`/recipes`)
          entrypoints: rest-internal
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: backend
precommit: |
  elixir --version
  mix format
  mix compile --warnings-as-errors
  mix credo --strict
  mix test
  MIX_ENV=prod mix release --overwrite
test: mix test
prettier:
  ignore:
    - mix.exs
    - mix.lock
    - "*.ex"
    - "*.exs"
