# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
extends: dcc://go
devcontainer:
  publish:
    image: ghcr.io/dhhyi/recipe-db-devcontainer-recipes
    labels:
      org.opencontainers.image.source: https://github.com/dhhyi/recipe-db
  initialize: go mod download -x
  ports:
    - 5000
  environment:
    TESTING: "true"
vscode:
  settings:
    peacock.remoteColor: "#730e31"
  extensions:
    - johnpapa.vscode-peacock
extras:
  - traefik
  - named-volumes
namedVolumes:
  $HOME/go/pkg/mod/cache: recipe-db-recipes-go-cache
traefik:
  network: intranet
  labels:
    http:
      services:
        recipe-db-recipes:
          loadBalancer:
            healthCheck:
              interval: 10s
              timeout: 1s
              path: /health
      routers:
        recipes:
          rule: PathPrefix(`/recipes`)
          entrypoints: rest-internal
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: backend
precommit: |
  go fmt
  go build -o precommit.out
  stat precommit.out
prettier:
  ignore:
    - go.mod
    - go.sum
    - "*.go"
