# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
extends: dcc://debian
devcontainer:
  publish:
    image: ghcr.io/dhhyi/recipe-db-devcontainer-frontend
    labels:
      org.opencontainers.image.source: https://github.com/dhhyi/recipe-db
  build:
    user:
      - RUN mise use -g go@1.25
      - RUN go install github.com/a-h/templ/cmd/templ@latest
      - RUN go install golang.org/x/tools/gopls@latest
  ports:
    - 3000
  environment:
    TESTING: "true"
  initialize: |
    go mod download -x
    templ generate
    go run github.com/Khan/genqlient@main
vscode:
  settings:
    peacock.remoteColor: "#f2b20f"
    "[templ]":
      editor.defaultFormatter: a-h.templ
    emmet.includeLanguages:
      templ: html
    tailwindCSS.includeLanguages:
      templ: html
    filewatcher.commands:
      - match: "\\.graphqls?"
        cmd: cd ${workspaceRoot} && go run github.com/Khan/genqlient@main
        event: onFileChange
  extensions:
    - johnpapa.vscode-peacock
    - appulate.filewatcher
    - golang.Go
    - a-h.templ
    - GraphQL.vscode-graphql
  tasks:
    - label: Run watch server
      command: templ generate --watch --cmd="go run ."
extras:
  - traefik
  - named-volumes
namedVolumes:
  $HOME/go/pkg/mod/cache: recipe-db-frontend-go-cache
traefik:
  network: intranet
  labels:
    http:
      services:
        recipe-db-frontend:
          loadBalancer:
            healthCheck:
              interval: 10s
              timeout: 1s
              path: /health
      routers:
        frontend:
          rule: PathPrefix(`/`)
          entrypoints: web
          middlewares: frontend-compress
      middlewares:
        frontend-compress:
          compress: true
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: frontend
precommit: |
  go version
  templ generate
  go fmt ./...
  go vet ./...
  go build -o main
  stat main
prettier:
  ignore:
    - go.mod
    - go.sum
    - "*.go"
    - "*.templ"
