# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
extends: dcc://javascript-pnpm
devcontainer:
  publish:
    image: ghcr.io/dhhyi/recipe-db-devcontainer-frontend
    labels:
      org.opencontainers.image.source: https://github.com/dhhyi/recipe-db
  initialize: |
    pnpm install
    npm run codegen
  ports:
    - 3000
  environment:
    TESTING: "true"
    GRAPHQL_ENDPOINT: http://traefik/graphql
vscode:
  settings:
    editor.defaultFormatter: esbenp.prettier-vscode
    peacock.remoteColor: "#f2b20f"
    filewatcher.commands:
      - match: "\\.graphql"
        cmd: cd ${workspaceRoot} && npm run codegen
        event: onFolderChange
  extensions:
    - johnpapa.vscode-peacock
    - GraphQL.vscode-graphql
    - esbenp.prettier-vscode
    - appulate.filewatcher
    - astro-build.astro-vscode
    - bradlc.vscode-tailwindcss
    - svelte.svelte-vscode
    - vue.volar
extras:
  - named-volumes
  - traefik
namedVolumes:
  node_modules: recipe-db-frontend-node-modules
  /home/pnpm: recipe-db-pnpm-store
traefik:
  network: intranet
  labels:
    http:
      routers:
        frontend:
          rule: PathPrefix(`/`)
          entrypoints: web
          middlewares: frontend-compress
      middlewares:
        frontend-compress:
          compress: true
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: frontend
precommit: |
  npm run codegen
  npm run lint -- --fix
  npm run build
prettier:
  plugins:
    - prettier-plugin-astro
    - prettier-plugin-svelte
