fragment Rating on Rating {
  average
  count
}

fragment RecipeStub on Recipe {
  id
  name
  image {
    url
    thumbUrl
  }
  rating {
    ...Rating
  }
}

query Overview {
  recipes {
    ...RecipeStub
  }
  recipeEditOnline: isServiceOnline(name: "recipes-edit")
}

fragment InspirationsLink on Link {
  url
  extracted {
    title
    description
    canonical
    inlinedFavicon
  }
}

fragment RecipeDetail on Recipe {
  id
  name
  method
  image {
    url
    thumbUrl
  }
  ingredients {
    name
    amount
    unit
    optional
  }
  rating {
    ...Rating
  }
  inspirations {
    ...InspirationsLink
  }
}

query RecipeById($id: ID!) {
  recipe(id: $id) {
    ...RecipeDetail
  }
  recipeEditOnline: isServiceOnline(name: "recipes-edit")
  imageEditOnline: isServiceOnline(name: "images-edit")
}
