[tools]
jq = "latest"
node = "26"
"npm:@devcontainers/cli" = "latest"
shellcheck = "latest"
yq = "latest"
ytt = "latest"

[tasks.generate-docker-compose]
run = "sh .scripts/generate-docker-compose.sh"

[settings]
idiomatic_version_file_enable_tools = ["npm", "pnpm"]
