extends: dcc://javascript-pnpm
devcontainer:
  initialize: |
    pnpm install
    npm run codegen
  ports:
    - 4000
  environment:
    GRAPHQL_ENDPOINT: http://traefik/graphql
vscode:
  settings:
    editor.defaultFormatter: esbenp.prettier-vscode
    peacock.remoteColor: "#2d1130"
    filewatcher.commands:
      - match: "\\.graphql"
        cmd: cd ${workspaceRoot} && npm run codegen
        event: onFolderChange
  extensions:
    - johnpapa.vscode-peacock
    - GraphQL.vscode-graphql
    - esbenp.prettier-vscode
    - appulate.filewatcher
extras:
  - named-volumes
  - traefik
namedVolumes:
  node_modules: recipe-db-apollo-test-node-modules
  /home/pnpm: recipe-db-pnpm-store
traefik:
  network: intranet
test: |
  npm run codegen
  npx jest --ci --runInBand
precommit: |
  npm run codegen
  npm run lint -- --fix
