extends: dcc://deno
devcontainer:
  ports:
    - 8081
vscode:
  settings:
    peacock.remoteColor: "#241031"
  extensions:
    - johnpapa.vscode-peacock
extras:
  - traefik
traefik:
  network: intranet
  labels:
    http:
      routers:
        link-extract:
          rule: PathPrefix(`/link-extract`)
          entrypoints: rest-internal
prettier:
  ignore:
    - "*.ts"
precommit: |
  deno fmt
  deno lint
  deno task build
