# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
extends: dcc://deno
devcontainer:
  publish:
    image: ghcr.io/dhhyi/recipe-db-devcontainer-link-extract
    labels:
      org.opencontainers.image.source: https://github.com/dhhyi/recipe-db
  ports:
    - 8081
vscode:
  settings:
    peacock.remoteColor: "#241031"
  extensions:
    - johnpapa.vscode-peacock
extras:
  - traefik
  - named-volumes
namedVolumes:
  $HOME/.cache/deno: recipe-db-link-extract-deno-cache
traefik:
  network: intranet
  labels:
    http:
      services:
        recipe-db-link-extract:
          loadBalancer:
            healthCheck:
              interval: 10s
              timeout: 1s
              path: /health
      routers:
        link-extract:
          rule: PathPrefix(`/link-extract`)
          entrypoints: rest-internal
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: backend
prettier:
  ignore:
    - "*.ts"
precommit: |
  deno fmt
  deno lint
  deno task build
