# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
extends: dcc://io
devcontainer:
  publish:
    image: ghcr.io/dhhyi/recipe-db-devcontainer-ratings
    labels:
      org.opencontainers.image.source: https://github.com/dhhyi/recipe-db
  build:
    packages:
      - libsqlite3-dev
    user:
      - RUN eerie install https://github.com/IoLanguage/Socket.git
      - RUN eerie install https://github.com/IoLanguage/CGI.git
      - RUN eerie install https://github.com/IoLanguage/SQLite3.git
  ports:
    - 8456
  environment:
    TESTING: "true"
vscode:
  settings:
    peacock.remoteColor: "#13520a"
  extensions:
    - johnpapa.vscode-peacock
    - qwtel.sqlite-viewer
extras:
  - traefik
traefik:
  network: intranet
  labels:
    http:
      services:
        recipe-db-ratings:
          loadBalancer:
            healthCheck:
              interval: 10s
              timeout: 1s
              path: /health
      routers:
        ratings:
          rule: PathPrefix(`/ratings`)
          entrypoints: rest-internal
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: backend
prettier:
  ignore:
    - "*.io"
