extends: dcc://io
devcontainer:
  build:
    packages:
      - libsqlite3-dev
    user:
      - RUN eerie install https://github.com/IoLanguage/Socket.git
      - RUN eerie install https://github.com/IoLanguage/CGI.git
      - RUN eerie install https://github.com/IoLanguage/SQLite3.git
  ports:
    - 8456
  environment:
    TESTING: "true"
vscode:
  settings:
    peacock.remoteColor: "#13520a"
  extensions:
    - johnpapa.vscode-peacock
    - qwtel.sqlite-viewer
extras:
  - traefik
traefik:
  network: intranet
  labels:
    http:
      routers:
        ratings:
          rule: PathPrefix(`/ratings`)
          entrypoints: rest-internal
      #     middlewares: limit
      # middlewares:
      #   limit:
      #     buffering.maxRequestBodyBytes: 2048
      #     buffering.retryExpression: ResponseCode() == 400 && Attempts() < 2
prettier:
  ignore:
    - "*.io"
