# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
extends: dcc://debian
devcontainer:
  name: recipe-db-graphql
  publish:
    image: ghcr.io/dhhyi/recipe-db-devcontainer-graphql
    labels:
      org.opencontainers.image.source: https://github.com/dhhyi/recipe-db
  build:
    packages:
      - build-essential
      - pkg-config
      - libssl-dev
      - musl-tools
    user:
      - RUN mise use -g watchexec
      - RUN mise use -g rust@1.98.0
      - RUN rustup target add x86_64-unknown-linux-musl
  initialize: cargo fetch
  ports:
    - 4000
  environment:
    TESTING: "true"
    REST_ENDPOINT: http://traefik:3000
    TRAEFIK_ENTRYPOINTS: web,rest-internal
vscode:
  settings:
    peacock.remoteColor: "#dbdb94"
    "[rust]":
      editor.defaultFormatter: rust-lang.rust-analyzer
  extensions:
    - johnpapa.vscode-peacock
    - rust-lang.rust-analyzer
    - GraphQL.vscode-graphql
  tasks:
    - label: Run watch server
      command: watchexec -r -e rs,toml,lock -- cargo run
extras:
  - named-volumes
  - traefik
namedVolumes:
  $HOME/.cargo/registry: recipe-db-graphql-cargo-registry
  $HOME/.cargo/git: recipe-db-graphql-cargo-git
  target: recipe-db-graphql-target
traefik:
  network: intranet
  labels:
    http:
      services:
        recipe-db-graphql:
          loadBalancer:
            healthCheck:
              interval: 10s
              timeout: 1s
              path: /health
      routers:
        graphql:
          rule: PathPrefix(`/graphql`)
          entrypoints: web
      #     middlewares: graphql-stripprefix
      # middlewares:
      #   graphql-stripprefix:
      #     stripprefix:
      #       prefixes: /graphql
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: api
precommit: |
  cargo --version
  cargo fmt --check
  cargo clippy --all-targets -- -D warnings
  cargo build --release
prettier:
  ignore:
    - "*.rs"
    - Cargo.toml
    - Cargo.lock
