# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
extends: dcc://perl
devcontainer:
  publish:
    image: ghcr.io/dhhyi/recipe-db-devcontainer-image-inline
    labels:
      org.opencontainers.image.source: https://github.com/dhhyi/recipe-db
  build:
    packages:
      - libdancer2-perl
      - libswitch-perl
  ports:
    - 3000
vscode:
  settings:
    peacock.remoteColor: "#0c9c90"
  extensions:
    - johnpapa.vscode-peacock
extras:
  - traefik
traefik:
  network: intranet
  labels:
    http:
      routers:
        image-inline:
          rule: PathPrefix(`/image-inline`)
          entrypoints: rest-internal
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: backend
prettier:
  ignore:
    - "*.pl"
precommit: |
  perltidy -b *.pl
