# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
extends: dcc://perl
devcontainer:
  build:
    packages:
      - libdancer2-perl
      - libswitch-perl
  ports:
    - 3000
vscode:
  settings:
    peacock.remoteColor: "#0c9c90"
  extensions:
    - johnpapa.vscode-peacock
extras:
  - traefik
traefik:
  network: intranet
  labels:
    http:
      routers:
        image-inline:
          rule: PathPrefix(`/image-inline`)
          entrypoints: rest-internal
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: backend
needsInit: true
prettier:
  ignore:
    - "*.pl"
precommit: |
  perltidy -b *.pl
