# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
extends: dcc://javascript-pnpm
devcontainer:
  publish:
    image: ghcr.io/dhhyi/recipe-db-devcontainer-design
    labels:
      org.opencontainers.image.source: https://github.com/dhhyi/recipe-db
  build:
    packages:
      - nginx
      - libnginx-mod-http-perl
    args:
      NGINX_FORMATTER_VERSION: "2.3.0"
    root:
      - ADD https://github.com/soulteary/nginx-formatter/releases/download/v${NGINX_FORMATTER_VERSION}/nginx-formatter_${NGINX_FORMATTER_VERSION}_linux_amd64.tar.gz /tmp/nginx-formatter.tar.gz
      - RUN tar -xvf /tmp/nginx-formatter.tar.gz -C /tmp
        && mv /tmp/nginx-formatter /usr/local/bin/nginx-formatter
      - RUN rm -rf /etc/nginx/sites-enabled/default && chmod -R 777 /usr/share/nginx/html
    files:
      - type: script
        path: /usr/local/bin/distribute-styling
        content: |
          #!/bin/sh
          target="/usr/share/nginx/html"
          input="$1"
          rm -rf "$target"/*
          cp -Rfv "$input"/* "$target"/
  initialize: |
    sudo /etc/init.d/nginx start
    sudo ln -sf ${containerWorkspaceFolder}/nginx.conf /etc/nginx/conf.d/default.conf
    pnpm install
    pnpm build
    distribute-styling "${containerWorkspaceFolder}/dist"
  ports:
    - 80
  environment:
    TESTING: "true"
vscode:
  settings:
    editor.defaultFormatter: esbenp.prettier-vscode
    peacock.remoteColor: "#e024d1"
    filewatcher.commands:
      - match: "nginx.conf"
        cmd: sudo /etc/init.d/nginx reload
        event: onFileChange
      - match: "(\\.css|components\/.*)"
        cmd: cd ${workspaceRoot} && pnpm build && distribute-styling "${workspaceRoot}/dist"
        event: onFileChange
  extensions:
    - johnpapa.vscode-peacock
    - appulate.filewatcher
    - esbenp.prettier-vscode
extras:
  - named-volumes
  - traefik
  - tmux
namedVolumes:
  node_modules: recipe-db-design-node-modules
  /home/pnpm: recipe-db-pnpm-store
traefik:
  network: intranet
  labels:
    http:
      services:
        recipe-db-design:
          loadBalancer:
            healthCheck:
              interval: 10s
              timeout: 1s
              path: /health
      routers:
        design:
          rule: PathPrefix(`/design`)
          entrypoints: web
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: frontend
precommit: |
  npm --version
  npx storybook --version
  nginx-formatter -indent=4
  npm run build
prettier:
  ignore:
    - nginx.conf
