perl_set $real_css_file 'sub {
    my $request = shift;
    my $document_root = $request->variable("document_root");
    my ($file) = glob "$document_root/design/index-*.css";

    return "" unless defined $file;
    $file =~ s{^\Q$document_root\E}{};
    return $file;
}';

perl_set $real_js_file 'sub {
    my $request = shift;
    my $document_root = $request->variable("document_root");
    my ($file) = glob "$document_root/design/index-*.js";

    return "" unless defined $file;
    $file =~ s{^\Q$document_root\E}{};
    return $file;
}';

server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html; # Pfad zu deinem Web-Verzeichnis

    location = /design/styles.css {
        if ($real_css_file = "" ) {
            return 404;
        }

        add_header Cache-Control "no-store" always;
        return 302 "$scheme://$http_host$real_css_file";
    }

    location = /design/components.js {
        if ($real_js_file = "" ) {
            return 404;
        }

        add_header Cache-Control "no-store" always;
        return 302 "$scheme://$http_host$real_js_file";
    }

    location ~ ^/design/index-[a-zA-Z0-9_-]+\.(css|js)$ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location = /health {
        access_log off;
        add_header 'Content-Type' 'application/json';
        return 204;
    }

    location / {
        try_files $uri $uri/ =404;
    }

}