# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
extends: dcc://debian
devcontainer:
  name: recipe-db-image-inline-test
  publish:
    image: ghcr.io/dhhyi/recipe-db-devcontainer-image-inline-test
    labels:
      org.opencontainers.image.source: https://github.com/dhhyi/recipe-db
  build:
    args:
      RUBY_VERSION: "3"
      RSPEC_VERSION: "3.13.0"
      AIRBORNE_VERSION: "0.3.6"
    user:
      - RUN mise use -g ruby@$RUBY_VERSION
      - RUN gem install rspec -v $RSPEC_VERSION
      - RUN gem install airborne -v $AIRBORNE_VERSION
  environment:
    MISE_IGNORED_CONFIG_PATHS: "/workspaces/*/mise.toml"
    REST_API: http://traefik:3000
    FIXTURE_API: http://traefik:3000/image-inline-test-fixture
vscode:
  settings:
    window.title: "${dirty}${rootName}${separator}${profileName}${separator}"
    peacock.remoteColor: "#5dc95d"
  extensions:
    - johnpapa.vscode-peacock
extras:
  - traefik
traefik:
  network: intranet
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: test
check: ruby --version
test: rspec
prettier:
  ignore:
    - "*.rb"
    - "*.jpg"
    - "*.png"
