# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
extends: base://debian
devcontainer:
  publish:
    image: ghcr.io/dhhyi/recipe-db-devcontainer-images
    labels:
      org.opencontainers.image.source: https://github.com/dhhyi/recipe-db
  build:
    args:
      NIM_VERSION: "2.2.4"
    packages:
      - build-essential
      - ca-certificates
      - curl
      - xz-utils
    root:
      - ADD https://nim-lang.org/download/nim-${NIM_VERSION}-linux_x64.tar.xz /tmp/nim.tar.xz
      - RUN cd /opt && tar -xf /tmp/nim.tar.xz && mv nim-${NIM_VERSION} nim && rm /tmp/nim.tar.xz
      - ENV PATH=/opt/nim/bin:${PATH}
  ports:
    - 8000
  environment:
    TESTING: "true"
  initialize: nimble install -d -y
  selftest: |
    nim --version
    echo 'echo "Hello World!"' >/tmp/helloworld.nim
    nim c -r --hints:off /tmp/helloworld.nim
vscode:
  settings:
    peacock.remoteColor: "#e9211a"
  extensions:
    - nimlang.nimlang
    - johnpapa.vscode-peacock
extras:
  - traefik
  - named-volumes
namedVolumes:
  $HOME/.nimble: recipe-db-images-nimble-cache
traefik:
  network: intranet
  labels:
    http:
      services:
        recipe-db-images:
          loadBalancer:
            healthCheck:
              interval: 10s
              timeout: 1s
              path: /health
      routers:
        images:
          rule: PathPrefix(`/images`)
          entrypoints: rest-internal
        images-public:
          rule: PathPrefix(`/public`)
          entrypoints: web
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: backend
prettier:
  ignore:
    - "*.nim"
    - "*.nimble"
precommit: |
  nimpretty server.nim
  nimble build -d:release -y --threads:off
