# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
extends: dcc://debian
devcontainer:
  name: recipe-db-link-extract-test
  publish:
    image: ghcr.io/dhhyi/recipe-db-devcontainer-link-extract-test
    labels:
      org.opencontainers.image.source: https://github.com/dhhyi/recipe-db
  build:
    args:
      PYTHON_VERSION: "3"
    user:
      - RUN mise use -g python@$PYTHON_VERSION
      - RUN pip install --break-system-packages robotframework robotframework-requests robotframework-tidy
  environment:
    MISE_IGNORED_CONFIG_PATHS: "/workspaces/*/mise.toml"
    REST_API: http://traefik:3000
    FIXTURE_API: http://traefik:3000/link-extract-test-fixture
vscode:
  settings:
    window.title: "${dirty}${rootName}${separator}${profileName}${separator}"
    peacock.remoteColor: "#5d5dc9"
  extensions:
    - johnpapa.vscode-peacock
extras:
  - traefik
traefik:
  network: intranet
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: test
format: robotidy .
check: |
  python3 --version
  robot --dryrun --outputdir target .
prettier:
  ignore:
    - "*.robot"
    - target
test: robot --outputdir target .
