# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
extends: dcc://debian
devcontainer:
  name: recipe-db-inspirations-test
  publish:
    image: ghcr.io/dhhyi/recipe-db-devcontainer-inspirations-test
    labels:
      org.opencontainers.image.source: https://github.com/dhhyi/recipe-db
  build:
    root:
      - ADD --chmod=711 https://github.com/intercloud/venom/releases/download/intercloud-beta-11/venom.linux-amd64 /usr/local/bin/venom
  environment:
    MISE_IGNORED_CONFIG_PATHS: "/workspaces/*/mise.toml"
    REST_API: http://traefik:3000
vscode:
  settings:
    window.title: "${dirty}${rootName}${separator}${profileName}${separator}"
    peacock.remoteColor: "#5d93c9"
  extensions:
    - johnpapa.vscode-peacock
    - thiht.vscode-venom
extras:
  - traefik
traefik:
  network: intranet
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: test
test: sh venom-run
check: venom version
