# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
language:
  name: venom
  binary: venom-run
  version: venom version
devcontainer:
  build:
    root:
      - ADD --chmod=711 https://github.com/intercloud/venom/releases/download/intercloud-beta-11/venom.linux-amd64 /usr/local/bin/venom
    files:
      - type: script
        path: /usr/local/bin/venom-run
        content: |
          #!/bin/sh
          if [ -z "$REST_API" ]; then
            echo "REST_API is not set"
            exit 1
          fi
          if [ -z "$1" ]; then
            tests="."
          else
            tests="$*"
          fi
          exec venom run --var REST_API="$REST_API" --stop-on-failure $tests
  environment:
    REST_API: http://traefik:3000
vscode:
  settings:
    peacock.remoteColor: "#7de1ff"
  extensions:
    - johnpapa.vscode-peacock
    - thiht.vscode-venom
extras:
  - traefik
traefik:
  network: intranet
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: test
test: venom-run
