type Rating {
  average: Float
  count: Int
}

extend type Recipe {
  rating: Rating
}

extend type Query {
  rating(id: ID!): Rating
}

extend type Mutation {
  deleteRatingsForTesting: Boolean

  rate(id: ID!, rating: Int!, login: String!): Float
}
