extend type Recipe {
  inspirations: [Link]
}

extend input RecipeInput {
  inspirations: [String]
}

extend type Mutation {
  deleteInspirationsForTesting: Boolean

  setInspirations(id: ID!, inspirations: [String]!): Boolean
}
