# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
extends: dcc://lua
devcontainer:
  publish:
    image: ghcr.io/dhhyi/recipe-db-devcontainer-inspirations
    labels:
      org.opencontainers.image.source: https://github.com/dhhyi/recipe-db
  build:
    packages:
      - m4
      - libssl-dev
  ports:
    - 8800
  environment:
    TESTING: "true"
  initialize: |
    luarocks make --tree lua_modules
    luarocks install https://raw.githubusercontent.com/dhhyi/Milua/main/milua-0.1-1.rockspec --tree lua_modules
    luarocks path --tree lua_modules >> ~/.zshrc
vscode:
  settings:
    Lua.format.enable: false
    peacock.remoteColor: "#1db8e8"
  extensions:
    - johnpapa.vscode-peacock
extras:
  - traefik
  - named-volumes
namedVolumes:
  lua_modules: recipe-db-inspirations-lua-modules
traefik:
  network: intranet
  labels:
    http:
      services:
        recipe-db-inspirations:
          loadBalancer:
            healthCheck:
              interval: 10s
              timeout: 1s
              path: /health
      routers:
        inspirations:
          rule: PathPrefix(`/inspirations`)
          entrypoints: rest-internal
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: backend
prettier:
  ignore:
    - "*.lua"
    - "*.rockspec"
precommit: |
  lua-format *.lua -i
  lua-format *.rockspec -i --column-table-limit=1
  luacheck *.lua
