#!/usr/bin/env bash
set -euo pipefail

workspace_root=$(cd -- "$(dirname -- "$0")/.." && pwd -P)
cd "$workspace_root"

output=$(mktemp .BUILD.bazel.XXXXXX)
trap 'rm -f "$output"' EXIT

printf '%s\n' '# Generated by generate-bazel-build.sh. Do not edit it manually.' > "$output"

quote() {
  jq -Rn --arg value "$1" '$value'
}

for project_file in */.project.yaml; do
  project=${project_file%/.project.yaml}
  check=$(yq eval-all -r 'select(documentIndex == 1) | .check // ""' "$project_file")
  [[ -n "$check" ]] || continue
  format=$(yq eval-all -r 'select(documentIndex == 1) | .format // ""' "$project_file")

  files=()
  format_files=()
  declare -A included_files=()
  while IFS= read -r -d '' file; do
    [[ -f "$file" ]] || continue
    format_files+=("$file")
    case "${file##*/}" in
      README.md | Dockerfile | .dockerignore) continue ;;
    esac
    files+=("$file")
    included_files["$file"]=1
  done < <(git ls-files --cached --others --exclude-standard -z -- "$project/" | sort -z)

  graphql_schema=$(yq eval-all -r 'select(documentIndex == 1) | .graphqlSchema // ""' "$project_file")
  if [[ -n "$graphql_schema" ]]; then
    schema_file="$project/recipe-db.graphqls"
    if [[ ! -f "$schema_file" ]]; then
      printf 'Missing generated GraphQL schema: %s (run mise run sync)\n' "$schema_file" >&2
      exit 1
    fi
    if [[ -z ${included_files["$schema_file"]+x} ]]; then
      files+=("$schema_file")
      format_files+=("$schema_file")
    fi
  fi

  if [[ "$project" == design ]]; then
    for source_project_file in */.project.yaml; do
      source_project=${source_project_file%/.project.yaml}
      while IFS= read -r source; do
        [[ -n "$source" ]] || continue
        source_path="$source_project/$source"
        if [[ ! -e "$source_path" ]]; then
          printf 'Missing Tailwind source: %s (run mise run sync)\n' "$source_path" >&2
          exit 1
        fi
        if [[ -z ${included_files["$source_project_file"]+x} ]]; then
          files+=("$source_project_file")
          included_files["$source_project_file"]=1
        fi
        while IFS= read -r -d '' file; do
          [[ -f "$file" && -z ${included_files["$file"]+x} ]] || continue
          files+=("$file")
          included_files["$file"]=1
        done < <(git ls-files --cached --others --exclude-standard -z -- "$source_path" | sort -z)
      done < <(yq eval-all -r 'select(documentIndex == 1) | .tailwindSources // [] | .[]' "$source_project_file")
    done
  fi

  if [[ -n "$format" ]]; then
    {
      printf '\ngenrule(\n'
      printf '    name = "%s_format",\n' "$project"
      printf '    srcs = [\n'
      for file in "${format_files[@]}"; do
        printf '        %s,\n' "$(quote "$file")"
      done
      printf '        %s,\n' "$(quote .scripts/format-bazel.sh)"
      printf '        %s,\n' "$(quote .scripts/run-in-devcontainer.sh)"
      printf '        %s,\n' "$(quote mise.toml)"
      printf '    ],\n'
      printf '    outs = ["%s-format.tar"],\n' "$project"
      printf "    cmd = \"sh \$(location .scripts/format-bazel.sh) %s \$@\",\n" "$project"
      printf '    tags = ["local"],\n'
      printf ')\n'
    } >> "$output"
  fi

  {
    printf '\ngenrule(\n'
    printf '    name = "%s_precommit",\n' "$project"
    printf '    srcs = [\n'
    for file in "${files[@]}"; do
      printf '        %s,\n' "$(quote "$file")"
    done
    printf '        %s,\n' "$(quote .scripts/bazel-check.sh)"
    printf '        %s,\n' "$(quote .scripts/run-in-devcontainer.sh)"
    printf '        %s,\n' "$(quote mise.toml)"
    printf '    ],\n'
    printf '    outs = ["%s-precommit.ok"],\n' "$project"
    printf "    cmd = \"sh \$(location .scripts/bazel-check.sh) %s \$@\",\n" "$project"
    printf '    tags = ["local"],\n'
    printf ')\n'
  } >> "$output"
done

{
  printf '\ngenrule(\n'
  printf '    name = "shellcheck",\n'
  printf '    srcs = [\n'
  while IFS= read -r -d '' file; do
    [[ -f "$file" ]] || continue
    printf '        %s,\n' "$(quote "$file")"
  done < <(git ls-files --cached -z -- '*.sh' '*.bash')
  printf '    ],\n'
  printf '    tools = ["mise.toml"],\n'
  printf '    outs = ["shellcheck.ok"],\n'
  printf '    cmd = "mise exec -- shellcheck %s && touch %s",\n' "\$(SRCS)" "\$@"
  printf '    tags = ["local"],\n'
  printf ')\n'
} >> "$output"

if ! cmp -s "$output" BUILD.bazel; then
  mv "$output" BUILD.bazel
fi
