#!/usr/bin/env bash
set -euo pipefail

workspace_root=$(cd -- "$(dirname -- "$0")/.." && pwd -P)
cd "$workspace_root"

output=$(mktemp .BUILD.bazel.XXXXXX)
trap 'rm -f "$output"' EXIT

printf '%s\n' '# Generated by generate-bazel-build.sh. Do not edit it manually.' > "$output"

quote() {
  jq -Rn --arg value "$1" '$value'
}

emit_rule() {
  local name=$1 archive=$2 script=$3 dependency=$4
  shift 4
  {
    printf '\ngenrule(\n'
    printf '    name = "%s",\n' "$name"
    printf '    srcs = [\n'
    for file in "$@"; do
      printf '        %s,\n' "$(quote "$file")"
    done
    if [[ -n "$dependency" ]]; then
      printf '        %s,\n' "$(quote ":$dependency")"
    fi
    printf '        %s,\n' "$(quote "$script")"
    if [[ "$archive" == *.tar ]]; then
      printf '        %s,\n' "$(quote .scripts/bazel-artifacts.sh)"
    fi
    printf '        %s,\n' "$(quote .scripts/run-in-devcontainer.sh)"
    printf '        %s,\n' "$(quote mise.toml)"
    printf '    ],\n'
    printf '    outs = ["%s"],\n' "$archive"
    printf '    cmd = "sh %s %s %s' "\$(location $script)" "$project" "\$@"
    if [[ -n "$dependency" ]]; then
      printf ' %s' "\$(location :$dependency)"
    fi
    printf '",\n'
    printf '    tags = ["local"],\n'
    printf ')\n'
  } >> "$output"
}

for project_file in */.project.yaml; do
  project=${project_file%/.project.yaml}
  check=$(yq eval-all -r 'select(documentIndex == 1) | .check // ""' "$project_file")
  format=$(yq eval-all -r 'select(documentIndex == 1) | .format // ""' "$project_file")
  generators=$(yq eval-all -r 'select(documentIndex == 1) | .generate // [] | length' "$project_file")
  [[ -n "$check" || -n "$format" || "$generators" -gt 0 ]] || continue

  files=()
  format_files=()
  declare -A included_files=()
  while IFS= read -r -d '' file; do
    [[ -f "$file" ]] || continue
    format_files+=("$file")
    case "${file##*/}" in
      README.md | Dockerfile | .dockerignore) continue ;;
    esac
    files+=("$file")
    included_files["$file"]=1
  done < <(git ls-files --cached --others --exclude-standard -z -- "$project/" | sort -z)

  graphql_schema=$(yq eval-all -r 'select(documentIndex == 1) | .graphqlSchema // ""' "$project_file")
  if [[ -n "$graphql_schema" ]]; then
    schema_file="$project/$graphql_schema/recipe-db.graphqls"
    if [[ ! -f "$schema_file" ]]; then
      printf 'Missing generated GraphQL schema: %s (run mise run sync)\n' "$schema_file" >&2
      exit 1
    fi
    schema_file=$(realpath --relative-to="$workspace_root" "$schema_file")
    if [[ -z ${included_files["$schema_file"]+x} ]]; then
      files+=("$schema_file")
      format_files+=("$schema_file")
    fi
  fi

  if [[ "$project" == design ]]; then
    for source_project_file in */.project.yaml; do
      source_project=${source_project_file%/.project.yaml}
      while IFS= read -r source; do
        [[ -n "$source" ]] || continue
        source_path="$source_project/$source"
        if [[ ! -e "$source_path" ]]; then
          printf 'Missing Tailwind source: %s (run mise run sync)\n' "$source_path" >&2
          exit 1
        fi
        if [[ -z ${included_files["$source_project_file"]+x} ]]; then
          files+=("$source_project_file")
          included_files["$source_project_file"]=1
        fi
        while IFS= read -r -d '' file; do
          [[ -f "$file" && -z ${included_files["$file"]+x} ]] || continue
          files+=("$file")
          included_files["$file"]=1
        done < <(git ls-files --cached --others --exclude-standard -z -- "$source_path" | sort -z)
      done < <(yq eval-all -r 'select(documentIndex == 1) | .tailwindSources // [] | .[]' "$source_project_file")
    done
  fi

  generation_dependency=
  if [[ "$generators" -gt 0 ]]; then
    generation_dependency="${project}_generate"
    emit_rule "$generation_dependency" "$project-generate.tar" .scripts/generate-bazel.sh "" "${format_files[@]}"
  fi

  if [[ -n "$format" ]]; then
    emit_rule "${project}_format" "$project-format.tar" .scripts/format-bazel.sh "$generation_dependency" "${format_files[@]}"
  fi

  if [[ -n "$check" ]]; then
    emit_rule "${project}_check" "$project-check.ok" .scripts/bazel-check.sh "$generation_dependency" "${files[@]}"
    check_dependency=$generation_dependency
    if [[ -n "$format" ]]; then
      check_dependency="${project}_format"
    fi
    emit_rule "${project}_precommit" "$project-precommit.ok" .scripts/bazel-check.sh "$check_dependency" "${files[@]}"
  fi
done

{
  printf '\ngenrule(\n'
  printf '    name = "shellcheck",\n'
  printf '    srcs = [\n'
  while IFS= read -r -d '' file; do
    [[ -f "$file" ]] || continue
    printf '        %s,\n' "$(quote "$file")"
  done < <(git ls-files --cached --others --exclude-standard -z -- '*.sh' '*.bash' '*.bats' | sort -zu)
  printf '    ],\n'
  printf '    tools = ["mise.toml"],\n'
  printf '    outs = ["shellcheck.ok"],\n'
  printf '    cmd = "mise exec -- shellcheck %s && touch %s",\n' "\$(SRCS)" "\$@"
  printf '    tags = ["local"],\n'
  printf ')\n'
} >> "$output"

{
  printf '\ngenrule(\n'
  printf '    name = "test_scripts",\n'
  printf '    srcs = [\n'
  while IFS= read -r -d '' file; do
    [[ -f "$file" ]] || continue
    printf '        %s,\n' "$(quote "$file")"
  done < <(git ls-files --cached --others --exclude-standard -z -- .scripts/ | sort -zu)
  printf '    ],\n'
  printf '    tools = ["mise.toml", ".bazelversion"],\n'
  printf '    outs = ["test-scripts.ok"],\n'
  printf '    cmd = "mise run --raw test-scripts && touch %s",\n' "\$@"
  printf '    tags = ["local"],\n'
  printf ')\n'
} >> "$output"

if ! cmp -s "$output" BUILD.bazel; then
  mv "$output" BUILD.bazel
fi
