const fs = require("fs");
const cp = require("child_process");
const path = require("path");
const prettier = require("prettier");
const { globSync } = require("glob");
const {
  projectRoot,
  getAvailableProjects,
  languageFile,
  getProjectConfig,
} = require("./shared");

function searchForForbiddenFiles(availableProjects) {
  const forbiddenGitIgnores = globSync("**/.gitignore", {
    cwd: projectRoot,
  }).filter(
    (file) =>
      file !== ".gitignore" &&
      !availableProjects.some((project) => file === `${project}/.gitignore`),
  );
  if (forbiddenGitIgnores.length > 0) {
    console.error(
      `Forbidden .gitignore files found: ${forbiddenGitIgnores.join(", ")}`,
    );
    process.exit(1);
  }

  const gitLsFiles = cp
    .execSync("git ls-files")
    .toString()
    .split("\n")
    .filter((file) => file !== "");
  const forbiddenPrettierFiles = gitLsFiles.filter((file) =>
    /\/?(\.prettierignore|.*prettierrc.*|prettier\.config\..*)$/.test(file),
  );
  if (forbiddenPrettierFiles.length > 0) {
    console.error(
      `Forbidden files found: ${forbiddenPrettierFiles.join(", ")}`,
    );
    process.exit(1);
  }
}

const warning = (commentSign) =>
  `${commentSign} This file is generated by synchronize.js. Do not edit it manually.\n\n`;

function writeRootDockerIgnore() {
  const rootGitIgnore = fs.readFileSync(
    path.join(projectRoot, ".gitignore"),
    "utf8",
  );
  const recursiveIgnores = `
    # nested dependency and build output
    **/.git
    **/.devcontainer
    **/.pnpm-store
    **/.vscode
    **/dist
    **/elm-stuff
    **/node_modules
    **/storybook-static
    **/target
  `.replace(/^ +/gm, "");

  console.log(`Writing .dockerignore ...`);
  fs.writeFileSync(
    path.join(projectRoot, ".dockerignore"),
    warning("#") + rootGitIgnore + recursiveIgnores,
  );
}

function getTailwindSources(availableProjects) {
  const sourceDirectory = path.join(projectRoot, "design", "src");

  return availableProjects
    .flatMap((project) => {
      const projectDirectory = path.join(projectRoot, project);
      const tailwindSources = getProjectConfig(project).tailwindSources || [];

      return tailwindSources.map((source) => {
        const sourcePath = path.resolve(projectDirectory, source);
        const relativePath = path.relative(projectDirectory, sourcePath);
        const outsideProject =
          relativePath === ".." ||
          relativePath.startsWith(`..${path.sep}`) ||
          path.isAbsolute(relativePath);

        if (outsideProject) {
          throw new Error(
            `Tailwind source ${source} must be inside project ${project}`,
          );
        }
        if (!fs.existsSync(sourcePath)) {
          throw new Error(
            `Tailwind source ${project}/${source} does not exist`,
          );
        }
        const sourceStats = fs.statSync(sourcePath);
        if (!sourceStats.isFile() && !sourceStats.isDirectory()) {
          throw new Error(
            `Tailwind source ${project}/${source} must be a file or directory`,
          );
        }

        const relativeSourcePath = path.relative(sourceDirectory, sourcePath);
        const sourcePathForTailwind =
          relativeSourcePath === ""
            ? "."
            : relativeSourcePath.split(path.sep).join("/");
        const workspaceSourcePath = path
          .join(project, relativePath)
          .split(path.sep)
          .join("/");

        return {
          project,
          sourcePathForTailwind,
          workspaceSourcePath,
          workspaceSourcePathForTailwind: sourceStats.isDirectory()
            ? `${workspaceSourcePath}/**`
            : workspaceSourcePath,
        };
      });
    })
    .sort(({ sourcePathForTailwind: left }, { sourcePathForTailwind: right }) =>
      left.localeCompare(right),
    );
}

function writeTailwindSources(availableProjects) {
  const tailwindSources = getTailwindSources(availableProjects);
  const outputPath = path.join(
    projectRoot,
    "design",
    "src",
    "tailwind-sources.css",
  );
  const content =
    "/* This file is generated by synchronize.js. Do not edit it manually. */\n\n" +
    tailwindSources
      .map(({ sourcePathForTailwind }) => `@source "${sourcePathForTailwind}";`)
      .join("\n") +
    "\n";

  console.log(`Writing design/src/tailwind-sources.css ...`);
  fs.writeFileSync(outputPath, content);
  return tailwindSources;
}

function writeTailwindDockerInputs(tailwindSources) {
  const dockerfilePath = path.join(projectRoot, "design", "Dockerfile");
  const startMarker = "# BEGIN generated Tailwind Docker inputs";
  const endMarker = "# END generated Tailwind Docker inputs";
  const dockerfile = fs.readFileSync(dockerfilePath, "utf8");
  const start = dockerfile.indexOf(startMarker);
  const end = dockerfile.indexOf(endMarker);

  if (
    start === -1 ||
    end === -1 ||
    start >= end ||
    dockerfile.indexOf(startMarker, start + startMarker.length) !== -1 ||
    dockerfile.indexOf(endMarker, end + endMarker.length) !== -1
  ) {
    throw new Error(
      `Expected one ${startMarker} and ${endMarker} marker pair in design/Dockerfile`,
    );
  }

  const inputs = tailwindSources
    .filter(({ project }) => project !== "design")
    .map(
      ({ workspaceSourcePath }) =>
        `COPY ${JSON.stringify([workspaceSourcePath, `/${workspaceSourcePath}`])}`,
    );
  const generatedBlock = [
    startMarker,
    "# This section is generated by synchronize.js. Do not edit it manually.",
    "",
    ...inputs,
    endMarker,
  ].join("\n");

  console.log(`Writing generated Tailwind Docker inputs ...`);
  fs.writeFileSync(
    dockerfilePath,
    dockerfile.slice(0, start) +
      generatedBlock +
      dockerfile.slice(end + endMarker.length),
  );
}

function writePrettierIgnores(availableProjects) {
  const rootGitIgnore = fs.readFileSync(
    path.join(projectRoot, ".gitignore"),
    "utf8",
  );
  const extraIgnores = `
    # extra ignores
    pnpm-lock.yaml
    .gitkeep
    *.txt
  `.replace(/^ +/gm, "");

  const otherProjectsIgnores =
    "\n# extra runs\n" + availableProjects.join("\n") + "\n";

  console.log(`Writing .prettierignore ...`);
  fs.writeFileSync(
    path.join(projectRoot, ".prettierignore"),
    warning("#") +
      rootGitIgnore +
      extraIgnores +
      ".husky/_\n" +
      otherProjectsIgnores,
  );

  availableProjects.forEach((project) => {
    const localGitignorePath = path.join(projectRoot, project, ".gitignore");
    const localGitIgnore = fs.existsSync(localGitignorePath)
      ? "\n# local\n" + fs.readFileSync(localGitignorePath, "utf8")
      : "";

    const projectConfig = getProjectConfig(project);
    const extraLocalIgnores =
      (projectConfig.prettier?.ignore || []).join("\n") + "\n";

    const outputFile = path.join(project, ".prettierignore");
    console.log(`Writing ${outputFile} ...`);
    fs.writeFileSync(
      path.join(projectRoot, outputFile),
      warning("#") +
        rootGitIgnore +
        localGitIgnore +
        extraIgnores +
        extraLocalIgnores,
    );
  });
}

async function writePrettierConfigs(availableProjects) {
  const rootPrettierConfigPath = path.join(projectRoot, ".prettierrc.cjs");

  const prettierConfig = async (plugins, overrides) => {
    const pluginsContent = `plugins: [${plugins
      .sort()
      .map((plugin) => `require.resolve("${plugin}")`)
      .join(", ")}],`;

    const overridesContent =
      overrides.length > 0
        ? `overrides: [${overrides
            .map(([files, options]) => JSON.stringify({ files, options }))
            .join(", ")}],`
        : "";

    const content =
      warning("//") +
      "module.exports = {" +
      pluginsContent +
      overridesContent +
      "}";

    return await prettier.format(content, { parser: "flow" });
  };

  const rootPrettierPlugins = ["prettier-plugin-sh", "@prettier/plugin-xml"];
  const sharedOverrides = [
    [
      ["*.svg"],
      {
        parser: "xml",
        xmlWhitespaceSensitivity: "ignore",
        xmlQuoteAttributes: "double",
        printWidth: 200,
      },
    ],
    [
      ["*.properties"],
      {
        parser: "sh",
      },
    ],
  ];

  const rootConfig = await prettierConfig(rootPrettierPlugins, [
    [[".husky/*-*"], { parser: "sh" }],
    [["LICENSE"], { parser: "markdown" }],
    ...sharedOverrides,
  ]);

  console.log(`Writing .prettierrc.cjs ...`);
  fs.writeFileSync(rootPrettierConfigPath, rootConfig);

  availableProjects.forEach(async (project) => {
    console.log(`Writing ${project}/.prettierrc.cjs ...`);
    const config = getProjectConfig(project);
    const extraPlugins = config.prettier?.plugins || [];
    const plugins = [...rootPrettierPlugins, ...extraPlugins];

    const projectPrettierConfigPath = path.join(
      projectRoot,
      project,
      ".prettierrc.cjs",
    );
    const projectPrettierConfig = await prettierConfig(
      plugins,
      sharedOverrides,
    );

    fs.writeFileSync(projectPrettierConfigPath, projectPrettierConfig);
  });
}

function writeDockerIgnores(availableProjects) {
  const rootGitIgnore =
    fs
      .readFileSync(path.join(projectRoot, ".gitignore"), "utf8")
      .split("\n")
      .filter((line) => line !== "recipe-db.graphqls")
      .join("\n") + "\n";

  const extras = `
    .project.yaml
    .gitignore
    README.md
  `.replace(/^ +/gm, "");

  availableProjects.forEach((project) => {
    if (fs.existsSync(path.join(projectRoot, project, "Dockerfile"))) {
      console.log(`Writing ${project}/.dockerignore ...`);

      const localGitIgnorePath = path.join(projectRoot, project, ".gitignore");
      const localGitIgnore = fs.existsSync(localGitIgnorePath)
        ? fs.readFileSync(localGitIgnorePath, "utf8") + "\n"
        : "";

      const localDockerIgnorePath = path.join(
        projectRoot,
        project,
        ".dockerignore",
      );
      const content = warning("#") + rootGitIgnore + localGitIgnore + extras;

      fs.writeFileSync(localDockerIgnorePath, content);
    }
  });
}

function writeDccFiles(availableProjects) {
  availableProjects.forEach((project) => {
    console.log(`Writing Devcontainer in ${project} ...`);
    const projectFile = languageFile(project);

    /** @type {string} */
    let commandLine;
    if (!fs.existsSync(path.join(project, ".update_devcontainer.sh")))
      commandLine = `curl -so- https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/bundle.js | node - ${projectFile} ${project}`;
    else commandLine = `sh -c 'cd ${project} && sh .update_devcontainer.sh'`;

    try {
      cp.execSync(commandLine, { cwd: projectRoot, encoding: "utf8" });
    } catch (e) {
      console.error(e.output?.join(""));
      console.error(e.message);
      process.exit(1);
    }
  });
}

function writeRootVSCodeSettingsFile(availableProjects, tailwindSources) {
  const tailwindIncludeLanguages = availableProjects.reduce(
    (languages, project) => ({
      ...languages,
      ...(getProjectConfig(project).vscode?.settings?.[
        "tailwindCSS.includeLanguages"
      ] || {}),
    }),
    {},
  );
  const elmClassRegexes = availableProjects.flatMap(
    (project) =>
      getProjectConfig(project).vscode?.settings?.["[elm]"]?.[
        "tailwindCSS.experimental.classRegex"
      ] || [],
  );
  const tailwindElmSettings =
    elmClassRegexes.length > 0
      ? {
          "[elm]": {
            "tailwindCSS.experimental.classRegex": elmClassRegexes,
          },
        }
      : {};
  const vscodeSettings = {
    "files.exclude": availableProjects.reduce(
      (acc, project) => ({
        ...acc,
        [`${project}/[!.]*`]: true,
      }),
      {},
    ),
    "files.associations": {
      "*.css": "tailwindcss",
    },
    "extensions.ignoreRecommendations": true,
    "task.autoDetect": "off",
    "tailwindCSS.experimental.configFile": {
      "design/src/design.css": tailwindSources.map(
        ({ workspaceSourcePathForTailwind }) => workspaceSourcePathForTailwind,
      ),
    },
    "tailwindCSS.includeLanguages": tailwindIncludeLanguages,
    ...tailwindElmSettings,
    "runOnSave.commands": [
      {
        match: "(^|/)\\.gitignore$|^\\.scripts/synchronize\\.js$",
        command:
          // eslint-disable-next-line no-template-curly-in-string
          "cd ${workspaceFolder} && node .scripts/synchronize.js --no-dcc",
        runningStatusMessage: "synchronizing...",
        finishStatusMessage: "synchronizing ✔",
      },
      {
        match: ".scripts/synchronize\\.js$",
        command:
          // eslint-disable-next-line no-template-curly-in-string
          "cd ${workspaceFolder} && node .scripts/synchronize.js --no-dcc",
        runningStatusMessage: "synchronizing...",
        finishStatusMessage: "synchronizing ✔",
      },
      ...availableProjects.map((project) => ({
        match: `/${project}/\\.project\\.yaml$`,
        // eslint-disable-next-line no-template-curly-in-string
        command: `cd \${workspaceFolder} && node .scripts/synchronize.js --no-dcc && sh ${project}/.update_devcontainer.sh`,
        runningStatusMessage: `${project} devcontainer...`,
        finishStatusMessage: `${project} devcontainer ✔`,
      })),
    ],
  };
  console.log(`Writing .vscode/settings.json ...`);
  fs.mkdirSync(path.join(projectRoot, ".vscode"), { recursive: true });
  fs.writeFileSync(
    path.join(projectRoot, ".vscode/settings.json"),
    JSON.stringify(vscodeSettings, null, 2),
  );
}

const args = process.argv.slice(2);

const projectsFromCommandLine = args.filter(
  (dir) =>
    fs.existsSync(path.join(projectRoot, dir)) &&
    fs.lstatSync(path.join(projectRoot, dir)).isDirectory(),
);

const allAvailableProjects = getAvailableProjects();
const availableProjects =
  projectsFromCommandLine?.length > 0
    ? projectsFromCommandLine
    : allAvailableProjects;

searchForForbiddenFiles(allAvailableProjects);

const tailwindSources = writeTailwindSources(allAvailableProjects);
writeTailwindDockerInputs(tailwindSources);
writeRootDockerIgnore();
writePrettierIgnores(availableProjects);
writePrettierConfigs(availableProjects);
writeDockerIgnores(availableProjects);
if (!args.includes("--no-dcc")) {
  writeDccFiles(availableProjects);
}
writeRootVSCodeSettingsFile(allAvailableProjects, tailwindSources);
