#!/bin/sh
set -eu

project_root=$(cd "$(dirname "$0")/.." && pwd)
cd "$project_root"

sources_css="design/src/tailwind-sources.css"
dockerfile="design/Dockerfile"
start_marker="# BEGIN generated Tailwind Docker inputs"
end_marker="# END generated Tailwind Docker inputs"

temporary_directory=$(mktemp -d)
trap 'rm -rf "$temporary_directory"' EXIT

entries="$temporary_directory/entries"
: > "$entries"

for project_file in */.project.yaml; do
  project=${project_file%/.project.yaml}

  mise exec -- yq -r \
    'select(documentIndex == 1) | .tailwindSources // [] | .[]' \
    "$project_file" \
    | while IFS= read -r source; do
      [ -n "$source" ] || continue

      case "$source" in
        /* | ../* | */../* | */.. | ..)
          echo "Tailwind source $source must be inside project $project" >&2
          exit 1
          ;;
      esac

      workspace_path="$project/$source"
      if [ ! -f "$workspace_path" ] && [ ! -d "$workspace_path" ]; then
        echo "Tailwind source $workspace_path must be an existing file or directory" >&2
        exit 1
      fi

      # @source paths are resolved relative to the stylesheet in design/src
      case "$workspace_path" in
        design/src/*) tailwind_path=${workspace_path#design/src/} ;;
        design/*) tailwind_path="../${workspace_path#design/}" ;;
        *) tailwind_path="../../$workspace_path" ;;
      esac

      printf '%s\t%s\t%s\n' "$tailwind_path" "$project" "$workspace_path" >> "$entries"
    done
done

LC_ALL=C sort -o "$entries" "$entries"

echo "Writing $sources_css ..."
{
  echo "/* This file is generated by sync-tailwind.sh. Do not edit it manually. */"
  echo
  cut -f1 "$entries" | sed 's|.*|@source "&";|'
} > "$sources_css"

block="$temporary_directory/block"
{
  echo "$start_marker"
  echo "# This section is generated by sync-tailwind.sh. Do not edit it manually."
  echo
  awk -F'\t' '$2 != "design" { printf "COPY [\"%s\",\"/%s\"]\n", $3, $3 }' "$entries"
  echo "$end_marker"
} > "$block"

echo "Writing generated Tailwind Docker inputs in $dockerfile ..."
awk -v block="$block" -v start="$start_marker" -v end="$end_marker" -v file="$dockerfile" '
  $0 == start {
    starts++
    if (starts == 1) {
      while ((getline line < block) > 0) print line
      skipping = 1
      next
    }
  }
  $0 == end {
    ends++
    if (skipping) {
      skipping = 0
      next
    }
  }
  !skipping
  END {
    if (starts != 1 || ends != 1) {
      printf "expected exactly one marker pair in %s\n", file > "/dev/stderr"
      exit 1
    }
  }
' "$dockerfile" > "$temporary_directory/dockerfile"
mv "$temporary_directory/dockerfile" "$dockerfile"
