#!/bin/sh
set -eu

project_root=$(cd "$(dirname "$0")/.." && pwd)
cd "$project_root"

warning="# This file is generated by sync-ignore-files.sh. Do not edit it manually."

temporary_directory=$(mktemp -d)
trap 'rm -rf "$temporary_directory"' EXIT

projects=$(for project_file in */.project.yaml; do
  echo "${project_file%/.project.yaml}"
done)

prefix_ignore_rules() {
  awk -v project="$1" '
    $0 == "" || substr($0, 1, 1) == "#" { print; next }
    {
      line = $0
      negation = ""
      if (substr(line, 1, 1) == "!") {
        negation = "!"
        line = substr(line, 2)
      }
      if (substr(line, 1, 1) == "/") separator = ""
      else if (index(line, "/") > 0) separator = "/"
      else separator = "/**/"
      print negation "/" project separator line
    }
  '
}

project_prettier_ignores() {
  mise exec -- yq -r \
    'select(documentIndex == 1) | .prettier.ignore // [] | .[]' \
    "$1/.project.yaml"
}

echo "Writing .dockerignore ..."
{
  echo "$warning"
  echo
  cat .gitignore
  cat << 'EOF'

# nested dependency and build output
**/.git
**/.devcontainer
**/.pnpm-store
**/.vscode
**/dist
**/elm-stuff
**/node_modules
**/storybook-static
**/target
EOF
} > .dockerignore

echo "Writing .prettierignore ..."
{
  echo "$warning"
  echo
  cat .gitignore
  cat << 'EOF'

# extra ignores
pnpm-lock.yaml
.gitkeep
*.txt
EOF

  for project in $projects; do
    extra_ignores=$(project_prettier_ignores "$project")
    printf '\n# %s\n' "$project"
    {
      if [ -f "$project/.gitignore" ]; then
        cat "$project/.gitignore"
        if [ -n "$extra_ignores" ]; then
          echo
        fi
      fi
      if [ -n "$extra_ignores" ]; then
        printf '%s' "$extra_ignores"
      fi
    } | prefix_ignore_rules "$project"
    if [ -z "$extra_ignores" ]; then
      echo
    fi
  done
} > .prettierignore

for project in $projects; do
  rm -f "$project/.prettierignore"
done

# the merged schema is generated into the projects, so it must not be excluded there
root_gitignore="$temporary_directory/root-gitignore"
grep -v '^recipe-db\.graphqls$' .gitignore > "$root_gitignore"

for project in $projects; do
  [ -f "$project/Dockerfile" ] || continue

  echo "Writing $project/.dockerignore ..."
  {
    echo "$warning"
    echo
    cat "$root_gitignore"
    echo
    if [ -f "$project/.gitignore" ]; then
      cat "$project/.gitignore"
      echo
    fi
    cat << 'EOF'

.project.yaml
.gitignore
README.md
EOF
  } > "$project/.dockerignore"
done
