# yaml-language-server: $schema=https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/language_schema.json
extends: dcc://debian
devcontainer:
  name: recipe-db-recipes-test
  publish:
    image: ghcr.io/dhhyi/recipe-db-devcontainer-recipes-test
    labels:
      org.opencontainers.image.source: https://github.com/dhhyi/recipe-db
  build:
    user:
      - RUN mise use -g java@21 maven@3.9.16
  environment:
    REST_API: http://traefik:3000
vscode:
  settings:
    window.title: "${dirty}${rootName}${separator}${profileName}${separator}"
    peacock.remoteColor: "#c95d93"
  extensions:
    - johnpapa.vscode-peacock
    - vscjava.vscode-java-pack
extras:
  - traefik
traefik:
  network: intranet
---
# yaml-language-server: $schema=../.scripts/project-schema.json
category: test
test: mvn --batch-mode --no-transfer-progress test
precommit: |
  java --version
  mvn --version
  mvn --batch-mode --no-transfer-progress spotless:apply
prettier:
  ignore:
    - "*.java"
