name: Publish
concurrency:
  group: publish
  cancel-in-progress: true
on:
  push:
    branches:
      - main

jobs:
  test-and-publish:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_PARALLEL_LIMIT: 1
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - uses: pnpm/setup@v2
        with:
          cache: true
          version: "12"
          install: false

      - name: report versions
        run: |
          set -x
          node --version
          pnpm --version
          docker --version
          docker compose version

      - name: install @devcontainers/cli
        run: |
          pnpm i -g @devcontainers/cli@latest
          devcontainer --version

      - name: login to ghcr.io
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: create buildx builder
        run: docker buildx create --use

      - name: synchronize
        run: |
          echo "::group::pnpm install"
          pnpm i --frozen-lockfile
          echo "::endgroup::"

      - name: build dev images
        run: |
          echo "::group::docker-compose.yml"
          cat docker-compose.yml
          echo "::endgroup::"
          echo "::group::docker compose build"
          docker compose --profile development build
          echo "::endgroup::"

      - name: test projects
        run: |
          echo "::group::docker-compose.yml"
          cat docker-compose.yml
          echo "::endgroup::"
          echo "::group::docker compose up"
          docker compose up -d --wait || (docker compose logs && exit 1)
          echo "::endgroup::"
          echo "::group::docker compose ps"
          docker compose ps
          echo "::endgroup::"
          for project in $(ls */.project.yaml | xargs dirname); do
            test_cmd=$(yq eval 'select(documentIndex==1) | .test // ""' $project/.project.yaml)
            if [ -n "$test_cmd" ]; then
              echo "::group::test $project"
              pnpm in-devcontainer $project test
              echo "::endgroup::"
            fi
          done

      - name: build and push prod images
        run: |
          echo "::group::generate prod docker-compose.yml"
          npm run generate-docker-compose prod
          echo "::endgroup::"
          echo "::group::docker-compose.yml"
          cat docker-compose.yml
          echo "::endgroup::"
          echo "::group::docker compose build"
          docker compose build
          echo "::endgroup::"
          echo "::group::docker compose push"
          docker compose push
          echo "::endgroup::"

      - name: build and push devcontainers
        run: |
          for project in $(ls */.project.yaml | xargs dirname); do
            echo "::group::build and push devcontainer $project"
            sh $project/.update_devcontainer.sh --build --push-cache -vv
            echo "::endgroup::"
          done

      - name: precommit check
        run: |
          for project in $(ls */.project.yaml | xargs dirname); do
            echo "::group::precommit check $project"
            pnpm in-devcontainer $project precommit
            echo "::endgroup::"
          done
