name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: lts/Hydrogen

      - name: report versions
        run: |
          set -x
          node --version
          npm --version
          docker --version
          docker compose version

      - name: install pnpm
        run: npm i -g pnpm

      - name: synchronize
        run: |
          echo "::group::pnpm install"
          pnpm i --frozen-lockfile
          echo "::endgroup::"
          echo "::group::generate prod docker-compose.yml"
          npm run generate-docker-compose prod
          echo "::endgroup::"
          echo "::group::docker-compose.yml"
          cat docker-compose.yml
          echo "::endgroup::"

      - name: login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: build and push images
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_PARALLEL_LIMIT: 1
        run: |
          docker buildx create --use
          docker compose build
          docker compose push
